<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SalonSeeder extends Seeder
{
    public function run(): void
    {
        $salons = [
            [
                'salon_code' => 'SAL001',
                'type' => 1,
                'name' => 'サロン美髪渋谷 1',
                'furigana' => 'Saron bihatsu Shibuya',
                'address' => '1-1-1 Shibuya, Tokyo',
                'color_plus_point' => 10,
                'perm_plus_point' => 15,
                'status' => true,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'salon_code' => 'SAL002',
                'type' => 2,
                'name' => 'ビューティーサロン原宿 2',
                'furigana' => 'Byūtīsaron Harajuku',
                'address' => '2-2-2 Harajuku, Tokyo',
                'color_plus_point' => 12,
                'perm_plus_point' => 18,
                'status' => true,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'salon_code' => 'SAL003',
                'type' => 1,
                'name' => 'ヘアスタジオ新宿 3',
                'furigana' => 'Hea sutajio Shinjuku',
                'address' => '3-3-3 Shinjuku, Tokyo',
                'color_plus_point' => 20,
                'perm_plus_point' => 12,
                'status' => true,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'salon_code' => 'SAL004',
                'type' => 2,
                'name' => 'ラグジュアリービューティー銀座 4',
                'furigana' => 'Ragujuarībyūtī Ginza',
                'address' => '4-4-4 Ginza, Tokyo',
                'color_plus_point' => 15,
                'perm_plus_point' => 20,
                'status' => true,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'salon_code' => 'SAL005',
                'type' => 1,
                'name' => 'クイックカット池袋 5',
                'furigana' => 'Kuikkukatto Ikebukuro',
                'address' => '5-5-5 Ikebukuro, Tokyo',
                'color_plus_point' => 30,
                'perm_plus_point' => 18,
                'status' => true,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'salon_code' => 'SAL006',
                'type' => 1,
                'name' => 'スタイリッシュヘア中野 6',
                'furigana' => 'Sutairisshuhea Nakano',
                'address' => '6-6-6 Nakano, Tokyo',
                'color_plus_point' => 20,
                'perm_plus_point' => 14,
                'status' => false,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'salon_code' => 'SAL007',
                'type' => 2,
                'name' => 'ヘアデザイン品川 7',
                'furigana' => 'Hea dezain Shinagawa',
                'address' => '7-7-7 Shinagawa, Tokyo',
                'color_plus_point' => 11,
                'perm_plus_point' => 16,
                'status' => true,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'salon_code' => 'SAL008',
                'type' => 1,
                'name' => 'ビューティープラザ池袋 8',
                'furigana' => 'Byūtī puraza Ikebukuro',
                'address' => '8-8-8 Ikebukuro, Tokyo',
                'color_plus_point' => 13,
                'perm_plus_point' => 17,
                'status' => true,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'salon_code' => 'SAL009',
                'type' => 1,
                'name' => 'ヘアサロン秋葉原 9',
                'furigana' => 'Hea saron Akihabara',
                'address' => '9-9-9 Akihabara, Tokyo',
                'color_plus_point' => 17,
                'perm_plus_point' => 30,
                'status' => false,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'salon_code' => 'SAL010',
                'type' => 1,
                'name' => 'ラグジュアリー表参道 10',
                'furigana' => 'Ragujuarī Omotesandō',
                'address' => '10-10-10 Omotesando, Tokyo',
                'color_plus_point' => 16,
                'perm_plus_point' => 19,
                'status' => true,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('salons')->insert($salons);
    }
}
